parameters:
  - name: baseURL
    type: string

steps:
  - powershell: |
      $env:baseURL="${{parameters.baseURL}}"
      yarn workspace lighthouse ci:audit
    displayName: "Lighthouse Audit"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Lighthouse Audit"
    inputs:
      pathToPublish: "$(System.DefaultWorkingDirectory)/.lighthouse.html"
      artifactName: "Lighthouse"
    condition: succeededOrFailed()
