steps:
  - task: AzureFunctionApp@1
    displayName: Deploy API to Beta
    inputs:
      azureSubscription: $(azureDevOpsServiceConnection)
      appType: functionApp
      appName: func-my-mermaid-tales
      package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
      deployToSlotOrASE: true
      slotName: beta

  - task: AzureStaticWebApp@0
    displayName: Deploy Web to Prod
    inputs:
      workingDirectory: $(webDirectory)
      app_location: out
      output_location: out
      skip_app_build: true
      skip_api_build: true
      is_static_export: true
      azure_static_web_apps_api_token: $(staticWebAppDeploymentApiToken)

  - task: AzureCLI@2
    displayName: "Swap API Beta to Prod"
    inputs:
      azureSubscription: "$(azureDevOpsServiceConnection)"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az functionapp deployment slot swap \
          --resource-group rg-my-mermaid-tales \
          --name func-my-mermaid-tales \
          --slot beta \
          --target-slot production
